<a href="https://colab.research.google.com/github/lijp16/lijp16/blob/main/notebook0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.4.0+cu121


##Introduction to Tensors

###Creating


In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim


0

In [4]:
#get tensor back as python int
scalar.item()

7

In [5]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#martix
martix = torch.tensor([[7,8],
                      [9,10]])
martix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
martix.ndim

2

In [10]:
martix.shape

torch.Size([2, 2])

In [11]:
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

###Random tensors

 a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

In [14]:
 #creat a random tensor of size (3,4)
 random_tensor = torch.rand(3,4)
 random_tensor

tensor([[0.1066, 0.6673, 0.8549, 0.9791],
        [0.2113, 0.2417, 0.7045, 0.6190],
        [0.3645, 0.8335, 0.1876, 0.9892]])

In [15]:
#creat a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))#height,width,colour channels
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###01tensor

In [16]:
#create all 0 or all 1 tensor
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
zeros
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
ones.dtype

torch.float32

###creating a range of tensors and tensors-like

In [18]:
#use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
one_to_ten_2 = torch.arange(start=0,end=1000,step=77)
one_to_ten_2

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [20]:
#creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###tensor datatype
**Note**Tensor datatype is one of the 3 big issue with pytorch & dl:
1. Tensors not right datatype
2. Tensor not right shape
3. Tensor not on right device

In [21]:
tensor_none = torch.tensor([3.0,6.0,9.0],dtype=None,#what datatype is the tensor(e.g. float16,float32...)
                              device=None,#what device is tensor on
                              requires_grad=False)#whether or not track gradients with tensor operations
tensor_none

tensor([3., 6., 9.])

In [22]:
float_16_tensor = tensor_none.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [23]:
tensor_none*float_16_tensor

tensor([ 9., 36., 81.])

###gtting info from tensors(tensor atrtribute)

1. datatype: tensor.dtype
2. devices: tensor.device
3. shape: tensor.shape

In [29]:
#creat a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0403, 0.9695, 0.6322, 0.2115],
        [0.6828, 0.5920, 0.4022, 0.0844],
        [0.7945, 0.2077, 0.8972, 0.7539]])

In [26]:
#get info
print(some_tensor)
print(f"dtype: {some_tensor.dtype}")
print(f"shape: {some_tensor.shape}")
print(f"device: {some_tensor.device}")

tensor([[0.7556, 0.2057, 0.5233, 0.9866],
        [0.9812, 0.5130, 0.1070, 0.1226],
        [0.3409, 0.7422, 0.9590, 0.6307]])
dtype: torch.float32
shape: torch.Size([3, 4])
device: cpu


###Manipulating Tensors(tensor operations)（张量操作)

Tensor operations include:
* addition+
* subtraction-
* multiplication (element-wise)*
* division/
* matrix multiplication矩阵*




In [42]:
#creat a tensor and operate it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [43]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [44]:
tensor - 10

tensor([-9, -8, -7])

In [45]:
tensor * 10

tensor([10, 20, 30])

In [46]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [47]:
tensor

tensor([1, 2, 3])

In [48]:
#reassign tensor to change
tensor = tensor * 10
tensor

tensor([10, 20, 30])