<a href="https://colab.research.google.com/github/lijp16/lijp16/blob/main/notebook0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.4.0+cu121


##Introduction to Tensors

###Creating


In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim


0

In [4]:
#get tensor back as python int
scalar.item()

7

In [5]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#martix
martix = torch.tensor([[7,8],
                      [9,10]])
martix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
martix.ndim

2

In [10]:
martix.shape

torch.Size([2, 2])

In [11]:
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

###Random tensors

 a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

In [14]:
 #creat a random tensor of size (3,4)
 random_tensor = torch.rand(3,4)
 random_tensor

tensor([[0.4671, 0.8568, 0.7073, 0.3717],
        [0.7087, 0.6044, 0.2399, 0.0672],
        [0.7934, 0.4516, 0.3137, 0.6398]])

In [15]:
#creat a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))#height,width,colour channels
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###01tensor

In [16]:
#create all 0 or all 1 tensor
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
zeros
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
ones.dtype

torch.float32

###creating a range of tensors and tensors-like

In [18]:
#use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
one_to_ten_2 = torch.arange(start=0,end=1000,step=77)
one_to_ten_2

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [20]:
#creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###tensor datatype
**Note**Tensor datatype is one of the 3 big issue with pytorch & dl:
1. Tensors not right datatype
2. Tensor not right shape
3. Tensor not on right device

In [21]:
tensor_none = torch.tensor([3.0,6.0,9.0],dtype=None,#what datatype is the tensor(e.g. float16,float32...)
                              device=None,#what device is tensor on
                              requires_grad=False)#whether or not track gradients with tensor operations
tensor_none

tensor([3., 6., 9.])

In [22]:
float_16_tensor = tensor_none.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [23]:
tensor_none*float_16_tensor

tensor([ 9., 36., 81.])

###gtting info from tensors(tensor atrtribute)

1. datatype: tensor.dtype
2. devices: tensor.device
3. shape: tensor.shape

In [24]:
#creat a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6914, 0.3059, 0.4428, 0.4753],
        [0.4659, 0.1733, 0.9888, 0.6191],
        [0.0048, 0.8256, 0.9100, 0.7694]])

In [25]:
#get info
print(some_tensor)
print(f"dtype: {some_tensor.dtype}")
print(f"shape: {some_tensor.shape}")
print(f"device: {some_tensor.device}")

tensor([[0.6914, 0.3059, 0.4428, 0.4753],
        [0.4659, 0.1733, 0.9888, 0.6191],
        [0.0048, 0.8256, 0.9100, 0.7694]])
dtype: torch.float32
shape: torch.Size([3, 4])
device: cpu


###Manipulating Tensors(tensor operations)（张量操作)

Tensor operations include:
* addition+
* subtraction-
* multiplication (element-wise)*
* division/
* matrix multiplication矩阵*




In [26]:
#creat a tensor and operate it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [27]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [28]:
tensor - 10

tensor([-9, -8, -7])

In [29]:
tensor * 10

tensor([10, 20, 30])

In [30]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [31]:
tensor

tensor([1, 2, 3])

In [32]:
#reassign tensor to change
tensor = tensor * 10
tensor

tensor([10, 20, 30])

###matrix multiplication

two main way:
1. element-wise multiplication(一个数乘一个矩阵)
2. matrix multiplication

2 main rule that proforming matrix multlication needs to satisfy:
1. the **inner dimensions** must match(靠内的两个数字相同能相乘):
* (3,2)@(3,2) error
* (3,2)@(2,3) work
* (2,3)@(3,2) work

2. the result of matrix multlication has the shape of **outer dimensions**(靠外的两个数字是结果的行列数):
* (3,2)@(2,3) -> (3,3)
* (2,3)@(3,2) -> (2,2)

In [33]:
#element-wise
print(tensor,"*",tensor)
print(f"equals:{tensor*tensor}")


tensor([10, 20, 30]) * tensor([10, 20, 30])
equals:tensor([100, 400, 900])


In [34]:
tensor = torch.tensor([1,2,3])
print(tensor)

tensor([1, 2, 3])


In [35]:
#matrix multiplication
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.06 ms, sys: 994 µs, total: 2.05 ms
Wall time: 10 ms


tensor(14)

**transpose**(转置矩阵)
switches the axes or dimensions of a given tensor
to fix the tensor shape issue

In [37]:
tensor_a = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_b = torch.tensor([[7,8],
                        [9,10],
                        [11,12]])


In [38]:
#torch.matmul(tensor_a,tensor_b)->error (3,2)*(3,2)->error
tensor_b

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [40]:
tensor_b.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [42]:
torch.matmul(tensor_a,tensor_b.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])