<a href="https://colab.research.google.com/github/lijp16/lijp16/blob/main/notebook0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.4.0+cu121


##Introduction to Tensors

###Creating


In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim


0

In [4]:
#get tensor back as python int
scalar.item()

7

In [5]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#martix
martix = torch.tensor([[7,8],
                      [9,10]])
martix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
martix.ndim

2

In [10]:
martix.shape

torch.Size([2, 2])

In [11]:
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

###Random tensors

 a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

In [14]:
 #creat a random tensor of size (3,4)
 random_tensor = torch.rand(3,4)
 random_tensor

tensor([[0.3152, 0.6374, 0.3139, 0.0132],
        [0.6169, 0.2639, 0.7056, 0.1569],
        [0.3935, 0.6411, 0.7795, 0.4399]])

In [15]:
#creat a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))#height,width,colour channels
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###01tensor

In [16]:
#create all 0 or all 1 tensor
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
zeros
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
ones.dtype

torch.float32

###creating a range of tensors and tensors-like

In [18]:
#use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
one_to_ten_2 = torch.arange(start=0,end=1000,step=77)
one_to_ten_2

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [20]:
#creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###tensor datatype
**Note**Tensor datatype is one of the 3 big issue with pytorch & dl:
1. Tensors not right datatype
2. Tensor not right shape
3. Tensor not on right device

In [21]:
tensor_none = torch.tensor([3.0,6.0,9.0],dtype=None,#what datatype is the tensor(e.g. float16,float32...)
                              device=None,#what device is tensor on
                              requires_grad=False)#whether or not track gradients with tensor operations
tensor_none

tensor([3., 6., 9.])

In [22]:
float_16_tensor = tensor_none.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [23]:
tensor_none*float_16_tensor

tensor([ 9., 36., 81.])

###gtting info from tensors(tensor atrtribute)

1. datatype: tensor.dtype
2. devices: tensor.device
3. shape: tensor.shape

In [24]:
#creat a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5610, 0.7146, 0.4164, 0.1813],
        [0.8192, 0.7026, 0.0366, 0.5707],
        [0.7258, 0.7269, 0.0258, 0.8656]])

In [25]:
#get info
print(some_tensor)
print(f"dtype: {some_tensor.dtype}")
print(f"shape: {some_tensor.shape}")
print(f"device: {some_tensor.device}")

tensor([[0.5610, 0.7146, 0.4164, 0.1813],
        [0.8192, 0.7026, 0.0366, 0.5707],
        [0.7258, 0.7269, 0.0258, 0.8656]])
dtype: torch.float32
shape: torch.Size([3, 4])
device: cpu


###Manipulating Tensors(tensor operations)（张量操作)

Tensor operations include:
* addition+
* subtraction-
* multiplication (element-wise)*
* division/
* matrix multiplication矩阵*




In [26]:
#creat a tensor and operate it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [27]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [28]:
tensor - 10

tensor([-9, -8, -7])

In [29]:
tensor * 10

tensor([10, 20, 30])

In [30]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [31]:
tensor

tensor([1, 2, 3])

In [32]:
#reassign tensor to change
tensor = tensor * 10
tensor

tensor([10, 20, 30])

###matrix multiplication

two main way:
1. element-wise multiplication(一个数乘一个矩阵)
2. matrix multiplication

2 main rule that proforming matrix multlication needs to satisfy:
1. the **inner dimensions** must match(靠内的两个数字相同能相乘):
* (3,2)@(3,2) error
* (3,2)@(2,3) work
* (2,3)@(3,2) work

2. the result of matrix multlication has the shape of **outer dimensions**(靠外的两个数字是结果的行列数):
* (3,2)@(2,3) -> (3,3)
* (2,3)@(3,2) -> (2,2)

In [33]:
#element-wise
print(tensor,"*",tensor)
print(f"equals:{tensor*tensor}")


tensor([10, 20, 30]) * tensor([10, 20, 30])
equals:tensor([100, 400, 900])


In [34]:
tensor = torch.tensor([1,2,3])
print(tensor)

tensor([1, 2, 3])


In [35]:
#matrix multiplication
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.7 ms, sys: 122 µs, total: 1.82 ms
Wall time: 5.26 ms


tensor(14)

**transpose**(转置矩阵)
switches the axes or dimensions of a given tensor
to fix the tensor shape issue

In [36]:
tensor_a = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_b = torch.tensor([[7,8],
                        [9,10],
                        [11,12]])


In [37]:
#torch.matmul(tensor_a,tensor_b)->error (3,2)*(3,2)->error
tensor_b

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [38]:
tensor_b.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [39]:
torch.matmul(tensor_a,tensor_b.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

###finding the min, max, mean, sum, etc(tensor aggregation)

In [40]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
torch.min(x)

tensor(0)

In [42]:
x.min()

tensor(0)

In [43]:
torch.max(x)

tensor(90)

In [44]:
#mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype
torch.mean(x.type(torch.float32))

tensor(45.)

In [45]:
torch.sum(x)

tensor(450)

###finding the positional min and max

In [46]:
x.argmin()

tensor(0)

In [47]:
x.argmax()

tensor(9)

1. reshaping - reshapes an input tensor to a difined shape
2. view - return a view of an input tensor of certain shape but keep the same memory as the original tensor
3. stacking - combine multiple tensors on the top of each other(vstack) or side by side(hstack)
4. squeeze - remove all 1 dimensions from a tensor
5. unsqueeze - add a 1 dimension to a target tensor
6. permute - return a view of the input with dimensions permuted(swapped) in  certain way

In [48]:
x = torch.arange(1.,10.)

In [49]:
x


tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [50]:
x.shape

torch.Size([9])

In [51]:
#add an extra dimension(改变行列式形状（x,y）xy=size(行列式项数))
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [52]:
x_reshaped = x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [53]:
#change the view  (x和z共享内存，改z会同时改x)
z = x.view(1,9)

In [54]:
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [55]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [56]:
#stack tensor on top of each other
x_stack = torch.stack([x,x,x,x],dim=0)
x_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [57]:
x_stack = torch.stack([x,x,x,x],dim=1)
x_stack

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [58]:
#squeeze(数据降维)
x_reshaped,x_reshaped.size()

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [59]:
x_squeeze = torch.squeeze(x_reshaped)
x_squeeze, x_squeeze.size()

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [60]:
# unsqueeze　数据升维
x_unsqueeze = torch.unsqueeze(x_squeeze,dim=1)
x_unsqueeze, x_unsqueeze.size()

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [61]:
#permute (改张量形状,共享内存如view）

x_org = torch.rand(size=(224,256,3))#height,width, colour_channel
x_permute = x_org.permute(2,1,0)# 改维数顺序
x_permute.size()#colour_channel,width,height

torch.Size([3, 256, 224])

##Indexing(selecting data from tensors)

Indexing with Pytorch is similar to indexing with Numpy

In [63]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [64]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [65]:
x[0][0]

tensor([1, 2, 3])

In [66]:
x[0][0][0]

tensor(1)

In [68]:
#can use":"to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [69]:
x[0,:,0]

tensor([1, 4, 7])

In [70]:
#return 9
x[0][2][2]

tensor(9)

In [74]:
#return 3,6,9
x[0,:,2]

tensor([3, 6, 9])

##PyTorch tensors & NumPy
NumPy is a popular scientific Python numerical computing library.
* Data in pytorch, want in Pytorch tensor ->torch.from_numpy(ndarray)
* Pytorch tensor ->Numpy ->torch.Tensor.numpy()

** numpy defult dtype is float 64 while pytorch is float 32

In [75]:
import torch
import numpy as np

#numpy->torch
array =  np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor



(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [76]:
array =  array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [79]:
#torch->numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [80]:
numpy_tensor.dtype


dtype('float32')

In [82]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))