<a href="https://colab.research.google.com/github/lijp16/lijp16/blob/main/notebook0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.4.0+cu121


##Introduction to Tensors

###Creating


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim


0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#martix
martix = torch.tensor([[7,8],
                      [9,10]])
martix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
martix.ndim

2

In [ ]:
martix.shape

torch.Size([2, 2])

In [ ]:
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

###Random tensors

 a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

In [ ]:
 #creat a random tensor of size (3,4)
 random_tensor = torch.rand(3,4)
 random_tensor

tensor([[0.7599, 0.2290, 0.3437, 0.2802],
        [0.0312, 0.1108, 0.2610, 0.9901],
        [0.9648, 0.0718, 0.9105, 0.2967]])

In [ ]:
#creat a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))#height,width,colour channels
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###01tensor

In [ ]:
#create all 0 or all 1 tensor
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
zeros
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

###creating a range of tensors and tensors-like

In [ ]:
#use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten_2 = torch.arange(start=0,end=1000,step=77)
one_to_ten_2

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
#creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###tensor datatype
**Note**Tensor datatype is one of the 3 big issue with pytorch & dl:
1. Tensors not right datatype
2. Tensor not right shape
3. Tensor not on right device

In [ ]:
tensor_none = torch.tensor([3.0,6.0,9.0],dtype=None,#what datatype is the tensor(e.g. float16,float32...)
                              device=None,#what device is tensor on
                              requires_grad=False)#whether or not track gradients with tensor operations
tensor_none

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = tensor_none.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)